spring.application.name=BARAJAS CLUB
server.port=8080

spring.thymeleaf.cache=false

# usa /var/data/uploads en Render y permite sobreescribir con APP_UPLOAD_DIR
app.upload-dir=/var/data/uploads

spring.web.resources.static-locations=/var/data/uploads

spring.servlet.multipart.location=/var/data/tmp
server.forward-headers-strategy=framework

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# H2 memoria
spring.datasource.url=jdbc:postgresql://10.1.4.149:5432/sistema_rifas
#postgresql://root:VWSdkSmwdGVWXJ8oQFw7cbO4rqP3jB6f@dpg-d3e0plbe5dus73fbifq0-a.oregon-postgres.render.com/sistema_rifas
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=VWSdkSmwdGVWXJ8oQFw7cbO4rqP3jB6f
#
## JPA/Hibernate
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=true
#
## Cargar data.sql despues del schema
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#
## H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


whatsapp.baseUrl=https://graph.facebook.com/v22.0
whatsapp.phoneNumberId=806998385835965
whatsapp.token=EAAQBkd4r6HEBPlMmmuCrXRt0m5VWHiZA8Wuw3lwZB3Bp5bTDacSDvr2967yrrmnrDg0ZAybxehg1vhV53z8YClLqGtYWvlI6IGJiQyQkYq2bh2gJIVUT8a8WJZC6KbvomPHZBwZBecCWQlvjWZBBLp9laDcHvgd1Itt7rZAVr6Hfvn0NEagRAOfety7NeZCKCLAZDZD
